### ISSUE TITLE
Continuation: smaller stepsize if solve goes bad?

### ISSUE THREAD

**Issue by ipelupessy** [BIMAU/fvm#4]
I think the interface.solve can go bad (ie takes too many iterations or doesn't converge) if the stepsize is too large? Is that correct? Maybe it is an idea to try: except around it and allow for a decrease in stepsize if this happens...
Now the same thing will probably happen but very indirect (e.g. solveer iterations overflow -> the solve is bad -> hence the newton will not converge -> too many newton iterations -> stepsie decrease)

**Comment by Sbte** [comment]
This is usually a sign of an underlying problem, not something we can solve by adapting something.

**Comment by Sbte** [comment]
This should not be a problem in practice. The step size increases/decreases gradually, and will be adjusted accordingly in every step. If it goes from 3 Newton iterations to not converging at all, a smaller ds will not help.
